DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE Authors(
    AuthorID BIGINT,
    BookID BIGINT references Books (BookID),
    AuthorName VARCHAR(255) NOT NULL,
    PRIMARY KEY (AuthorID)
);
CREATE TABLE Genres(
    GenreID BIGINT,
    BookID BIGINT references Books (BookID),
    Genre VARCHAR(255) NOT NULL,
    PRIMARY KEY (GenreID)
);
CREATE TABLE Books(
    BookID BIGINT,
    BookTitle VARCHAR(255) NOT NULL,
    AuthorID BIGINT,
    GenreID BIGINT,
    PRIMARY KEY (bookID)
);
