DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE Authors(AuthorID BIGINT NOT NULL, AuthorName VARCHAR(255), PRIMARY KEY (AuthorID),
                    CONSTRAINT FK_AuthorBook FOREIGN KEY (AuthorID) REFERENCES Books(AuthorID));
CREATE TABLE Genres(GenreID BIGINT NOT NULL, Genre VARCHAR(255), PRIMARY KEY (GenreID),
                    CONSTRAINT FK_GenreBook FOREIGN KEY (GenreID) REFERENCES Books(GenreID));
CREATE TABLE Books(BookID BIGINT NOT NULL, BookTitle VARCHAR(255), AuthorID BIGINT, GenreID BIGINT, PRIMARY KEY (bookID),
                    CONSTRAINT FK_BookAuthor FOREIGN KEY (AuthorID) REFERENCES Authors(AuthorID),
                    CONSTRAINT FK_BookGenre FOREIGN KEY (GenreID) REFERENCES Genres(GenreID));
