DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE Authors(AuthorID BIGINT NOT NULL, AuthorName VARCHAR(255), PRIMARY KEY (AuthorID));
CREATE TABLE Genres(GenreID BIGINT NOT NULL, Genre VARCHAR(255), PRIMARY KEY (GenreID));
CREATE TABLE Books(BookID BIGINT NOT NULL, BookTitle VARCHAR(255), AuthorID BIGINT, GenreID BIGINT, PRIMARY KEY (bookID));
